apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging
namePrefix: staging-

images:
  - name: REPLACE_IMAGE
    newName: ghcr.io/your-org/node-app
    newTag: latest
